# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('especificaiones', models.CharField(max_length=200)),
                ('debe', models.FloatField()),
                ('haber', models.FloatField()),
            ],
        ),
    ]
